import Head from 'next/head';
// import Image from 'next/image';
import styled from '@emotion/styled';

import Header from '../components/common/Header';
import Community from '../components/community/Community';
import MainA from '../components/mainA/MainA';
import MainB from '../components/mainB/MainB';
import MainC from '../components/mainC/MainC';

const StyledMain = styled.main`
  width: 1200px;
  min-height: 100vh;
  margin: 0 auto;

  @media (max-width: 1024px) {
    width: 100%;
    padding: 0 1rem;
  }
`;

const StyledFooter = styled.footer``;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Block Community</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <StyledMain>
        <Community />
        <div style={{ display: 'flex' }}>
          <MainA />
          <MainB />
          <MainC />
        </div>
      </StyledMain>

      <StyledFooter>
        {/* <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a> */}
      </StyledFooter>
    </div>
  );
}
