import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import Header from '../components/common/Header';
import Community from '../components/community/Community';
import MainA from '../components/mainA/MainA';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Block Community</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <main className={styles.main}>
        <Community />
        <div style={{ display: 'flex' }}>
          <MainA />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
